### ISSUE TITLE
error on height

### ISSUE THREAD

**Issue by devakm** [crnormand/gurps#1517]
multilevel-tokens, levels, and wall-height have become de facto standards for dealing with height when designing scenes

https://foundryvtt.com/packages/multilevel-tokens/
https://foundryvtt.com/packages/wall-height/
https://foundryvtt.com/packages/levels

These modules add a height element to tokens, items, tiles, walls, etc. There is widespread support for this in many other modules.
Since switching to GGA I keep getting console errors about reading height:

```
TypeError: Cannot read properties of undefined (reading 'height')
[Detected 1 package: system:gurps]
    at GurpsActorSheet.setPosition (actor-sheet.js:1361:33)
    at GurpsActorSheet._render (foundry.js:3095:12)
    at async GurpsActorSheet._render (foundry.js:3764:5)
    at async GurpsActorSheet._render (actor-sheet.js:53:5)
onError @ foundry.js:319
🎁call_wrapped @ libWrapper-wrapper.js:511
🎁Hooks.onError#lib-wrapper @ listeners.js:137
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
(anonymous) @ foundry.js:3023
Promise.then (async)
render @ foundry.js:3021
render @ foundry.js:4259
render @ foundry.js:10819
_forceRender @ actor.js:3574
(anonymous) @ actor.js:271
setTimeout (async)
calculateDerivedValues @ actor.js:271
prepareDerivedData @ actor.js:173
prepareData @ foundry.js:10772
prepareData @ actor.js:112
_postUpdateDocumentCallbacks @ foundry.js:10321
_handleUpdateDocuments @ foundry.js:10250
_updateDocuments @ foundry.js:10131
await in _updateDocuments (async)
update @ backend.mjs:154
await in update (async)
updateDocuments @ document.mjs:373
update @ document.mjs:456
update @ actor.js:817
accumulateDamageRoll @ actor.js:930
damage @ gurps.js:578
performAction @ gurps.js:1171
handleGurpslink @ gurps-wiring.js:141
chatClickGurpslink @ gurps-wiring.js:107
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

```
and less often:

```
Error: Failed to initialized Item [c3mn7wwxr2mu6b7l] in Actor [pO6qfln7CbJ7ZcpY]: The provided Item type must be in the array of types defined by the game system
    at ItemData._validateField (data.mjs:384:13)
    at ItemData.validate (data.mjs:275:14)
    at new DocumentData (data.mjs:48:10)
    at new ItemData (data.mjs:1010:1)
    at new Document (document.mjs:47:14)
    at new BaseItem (documents.mjs:684:1)
    at new <anonymous> (foundry.js:10541:5)
    at new Item (foundry.js:16680:1)
    at new GurpsItem (item.js:1:8)
    at EmbeddedCollection._initialize (embedded-collection.mjs:68:15)
    at new EmbeddedCollection (embedded-collection.mjs:53:10)
    at ActorData._initialize (data.mjs:189:24)
    at ActorData._initialize (data.mjs:188:11)
    at new DocumentData (data.mjs:51:10)
    at new ActorData (data.mjs:139:1)
    at new Document (document.mjs:47:14)
    at new BaseActor (documents.mjs:62:1)
    at new <anonymous> (foundry.js:10541:5)
    at new Actor (foundry.js:13402:5)
    at new GurpsActor (actor.js:66:8)
    at TokenDocument.getActor (foundry.js:18818:12)
    at get actor [as actor] (foundry.js:18735:26)
    at get actor [as actor] (foundry.js:37567:26)
    at GurpsToken.drawEffects (token.js:56:61)
    at GurpsToken.draw (foundry.js:37975:16)
    at async GurpsToken.tokenDraw (module.js:47:5)
    at async Promise.all (index 22)
    at async TokenLayer.draw (foundry.js:22266:5)
    at async Canvas.draw (foundry.js:20116:11)
    at async Scene.view (foundry.js:17859:7)
    at async Game.initializeCanvas (foundry.js:5677:20)
    at async Game.setupGame (foundry.js:5548:5)
    at async Game._initializeGameView (foundry.js:6514:5)
    at async Game.initialize (foundry.js:5431:5)
```

Anything you can do to help reduce this error spam would be greatly appreciated

**Comment by devakm** [comment]
I suspect that GGA might be using a different height field than the foundry standard. Height is important in Levels and Multilevel Tokens because it determines which objects you have line of sight past. A short character may not be able to see over a low wall, where a large creature may be able to see out of a deep pit or reach a player that a halfling standing on the same surface could not see.

**Comment by crnormand** [comment]
No, the 'height' mentioned is the height of the character sheet.. it has nothing to do with the actor's game height.  I've added code to protect when a bad position is sent to the sheet (to reposition).

As for the second error... that is a data error.   We only have 1 Item type... there is no way to create an Item of a different type (unless it is coming from outside module).   We have seen this before... when the Foundry persistence got corrupted.   The only fix for this it to delete the Actor (which will delete all of the associated items), and re-import the Actor.   Sorry.

**Comment by devakm** [comment]
> As for the second error... that is a data error. We only have 1 Item type... there is no way to create an Item of a different type (unless it is coming from outside module). We have seen this before... when the Foundry persistence got corrupted. The only fix for this it to delete the Actor (which will delete all of the associated items), and re-import the Actor. Sorry.

Thanks, this makes sense and is similar to the workaround I settled on.
