### ISSUE TITLE
[BUG] Starting a combat using ForgeVTT hosting completely corrupts the map.

### ISSUE THREAD

**Issue by SethSylvester** [crnormand/gurps#1829]
Adding anyone to initative whether the combat starts or not gives an error that prevents reopening the map ever. Tested without any addons or modules.

```js
 foundry.js:747 TypeError: Canvas drawing failed: Cannot read properties of undefined (reading 'find'). Cannot read properties of undefined (reading 'find')
    at Maneuvers.isActiveEffectManeuver (maneuver.js:332:34)
    at maneuver.js:341:53
    at Array.filter (<anonymous>)
    at Maneuvers.getActiveEffectManeuvers (maneuver.js:341:30)
    at GurpsToken.drawEffects (token.js:53:31)
    at GurpsToken._draw (foundry.js:46239:16)
    at async GurpsToken.draw (foundry.js:25258:5)
    at async Promise.all (index 0)
    at async TokenLayer._draw (foundry.js:30889:5)
    at async TokenLayer._draw (foundry.js:37125:5)
onError @ foundry.js:747 `

Canvas drawing failed: Cannot read properties of undefined (reading 'find')
fetch @ foundry.js:59246

Uncaught (in promise) TypeError: Cannot set properties of null (setting 'visible')
    at SoundsLayer._deactivate (foundry.js:30948:26)
    at SoundsLayer.deactivate (foundry.js:30533:10)
    at TokenLayer.activate (foundry.js:30497:76)
    at #initializeCanvasLayer (foundry.js:23905:11)
    at #initialize (foundry.js:23855:32)
    at Canvas.draw (foundry.js:23748:29)
    at async Scene.view (foundry.js:20901:7)

**Comment by SethSylvester** [comment]
Closing this as the issue appears resolved after forcing Forge to use Foundry 11 for anyone who might be having this same issue.
