### ISSUE TITLE
Multiple errors with 0.16.1 and 0.16.2 relating to drawing canvas - effectively prevents the game from running

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#1834]
Found this issue with 0.16.1 and assumed 0.16.2 would resolve but after a short break came back to it and found it isn't resolved.  There is no issue with 0.16.0 and earlier.  This is with FVTT V10, Patch 7, Build 303.

The errors all occur when trying to load a scene, it doesn't matter if it's a new scene or an old one, or one made fresh.  Errors such as:

![image](https://github.com/crnormand/gurps/assets/89975749/03b9b117-c901-467b-a027-123872c89ae7)
![image](https://github.com/crnormand/gurps/assets/89975749/705c6117-553b-438e-b5f1-3542a36b94fd)

These are example errors from the console:

`foundry.js:727 Foundry VTT | Error thrown in hooked function 'updateDragResistance' for hook 'canvasPan'
#call @ foundry.js:727
foundry.js:747 TypeError: Error thrown in hooked function 'updateDragResistance' for hook 'canvasPan'. Cannot read properties of undefined (reading 'options')
    at Object.updateDragResistance [as fn] (zoom-pan-options.js:298:36)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Canvas.pan (foundry.js:24065:11)
    at Canvas._onResize (foundry.js:24701:10)
    at _onWindowResize (foundry.js:8923:47)
onError @ foundry.js:747
button:1 Access to internal resource at 'https://github.com/manifest.json' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

`foundry.js:747 TypeError: Canvas drawing failed: Cannot read properties of undefined (reading 'find'). Cannot read properties of undefined (reading 'find')
    at Maneuvers.isActiveEffectManeuver (maneuver.js:332:34)
    at maneuver.js:341:53
    at Array.filter (<anonymous>)
    at Maneuvers.getActiveEffectManeuvers (maneuver.js:341:30)
    at GurpsToken.drawEffects (token.js:53:31)
    at GurpsToken._draw (foundry.js:46239:16)
    at async GurpsToken.draw (foundry.js:25258:5)
    at async Promise.all (index 1)
    at async TokenLayer._draw (foundry.js:30889:5)
    at async TokenLayer._draw (foundry.js:37125:5)
    at async TokenLayer.draw (foundry.js:30408:5)
    at async InterfaceCanvasGroup.draw (foundry.js:26210:9)
    at async InterfaceCanvasGroup.draw (foundry.js:39329:5)
    at async Canvas.draw (foundry.js:23732:11)
    at async Scene.view (foundry.js:20901:7)
onError @ foundry.js:747
foundry.js:59246 Canvas drawing failed: Cannot read properties of undefined (reading 'find')
fetch @ foundry.js:59246
foundry.js:30948 Uncaught (in promise) TypeError: Cannot set properties of null (setting 'visible')
    at SoundsLayer._deactivate (foundry.js:30948:26)
    at SoundsLayer.deactivate (foundry.js:30533:10)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at SoundsLayer.PlaceablesLayer_deactivate (ShowLayerControls.ts:151:24)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁PlaceablesLayer.prototype.deactivate#0 (libWrapper-wrapper.js:189:20)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁SoundsLayer.prototype.deactivate#df-architect (SoundCounter.ts:15:4)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁SoundsLayer.prototype.deactivate#0 (libWrapper-wrapper.js:189:20)
    at TokenLayer.activate (foundry.js:30497:76)
    at TokenLayer.activate (injection.js:134:18)
    at #initializeCanvasLayer (foundry.js:23905:11)
    at #initialize (foundry.js:23855:32)
    at Canvas.draw (foundry.js:23748:29)
    at async Scene.view (foundry.js:20901:7)`

It can be random and different for different users logged in, occasionally it all loads up correctly and maybe even for 2 users (GM or Players) but almost certainly not for all and then as soon as you change scenes or reload for some reason, the problem will strike again.

I looked at the issue KakaRoTo on The Forge (as I host with them) as I thought it might have been due to some issues their side, but he also confirmed it was GGA.

Reverting to 0.16.0 removes the issues completely.

**Comment by Farmeroz** [comment]
Thanks, Jeff.  You might want to update the details on The Forge, though:

![image](https://github.com/crnormand/gurps/assets/89975749/68cf5980-ef58-48d7-b515-65553fe49ad2)

Specifically lists Version 10 as compatible

**Comment by crnormand** [comment]
Odd... I thought Forge would pull from Foundry.  I deleted those versions to try to bypass that error.
