### ISSUE TITLE
Exported templates not imported

### ISSUE THREAD

**Issue by bristol454** [crnormand/gurps#1886]
When a character is created using a racial template using either GCA4 or GCA5 and then exported, then imported into the vtt the character sheet does not reflect the template contents and some items are missing.

For example:
Using GCA5:
1: Create new character and add the Petty Drake (Cute Shoulder Dragon) template.
2: Export to VTT
3: Import to VTT
4: Check VTT

Issues are as follows:

First, I have to refresh (F5) the VTT to see an updated character sheet.
Second, I cannot change movement modes as only ground is available, the  template has fly.
Third, the innate attack is missing.
Fourth, all the template traits are missing. I know that the Basic Set says to just write in the template BUT this is a primary character sheet 
     and should have all the info in it for player and GM reference.

**Comment by mjeffw** [comment]
> First, I have to refresh (F5) the VTT to see an updated character sheet.

The fact that you have to refresh Foundry tells me that the import failed with an exception. Are you still having this problem? If so, can you:

1. Attach a character file that exhibits the problem?
2. Reproduce the problem and look at the console for errors. If there is an error, please copy and paste it into a comment on this issue.

**Comment by bristol454** [comment]
Just checked the current behavior and here is what I have:
GCA4 and GGA 17.17B5
1: On import of a character with a template(petty Drake Test.gca4.txt)
[Petty Drake test.gca4.TXT](https://github.com/user-attachments/files/18402352/Petty.Drake.test.gca4.TXT)
I get the following error in the console:
foundry.js:655 Error: Failed data preparation for Actor.Tm5sPOKsVCQkNdCM. Cannot read properties of undefined (reading 'carried')
    at Hooks.onError (foundry.js:654:24)
    at GurpsActor._safePrepareData (foundry.js:10801:15)
    at GurpsActor._initialize (foundry.js:10630:19)
    at GurpsActor.updateSource (foundry-esm.js:10520:35)
    at #handleUpdateDocuments (foundry-esm.js:56579:13)
    at async GurpsActor.updateDocuments (foundry-esm.js:11473:23)
    at async GurpsActor.update (foundry-esm.js:11584:23)
    at async GurpsActor.update (actor.js:967:12)
    at async GurpsActor.internalUpdate (actor.js:989:5)
    at async ActorImporter.importActorFromGCA (actor-importer.js:484:7)

Also the following error is sent to chat:
[1/13/2025, 4:41:21 PM] Gamemaster
WARNING
An error occured while importing Sally. OLD, TypeError:Cannot read properties of undefined (reading 'carried'). The file version: 'GCA-11'. Current Versions: 'GCA-11' & '0'. Check the Users Guide for details on where to get the latest version. GURPS 4e Game Aid USERS GUIDE

2. The Petty drake template does not list their component parts. Upon further investigation the export file doesn't list the components either. Maybe the Export script could parse out the components somehow. Would be nice to have an option to hide the components in template container, put the template on the sheet with the components grouped in/under the template or break all the components out separately not associated with the template. The GCA4 Phoenix sheet has layout that works. If you are looking for inspiration. 
[Pettydraketest.pdf](https://github.com/user-attachments/files/18402491/Pettydraketest.pdf)

Not sure if that ask is in your wheelhouse or not.


3. Still cannot select flying as a movement mode AND the innate attack in the template is not showing up in the VTT.
