### ISSUE TITLE
[BUG] Characters cannot be opened until duplicated

### ISSUE THREAD

**Issue by SageThalcos** [crnormand/gurps#1890]
I'm having an issue that when I click on an Actor (from a token instance or the sidebar) nothing happens -- it does not pop up the character sheet. Duplicating the actor gets it working again, for a while, then it eventually stops working again.

Some more details:

- This only seems to happen on PC actors -- it does not happen to any NPCs that are not player controlled
- This only seems to happen on characters with Foundry-created items on them. If I remove the foundry-created items, the problem does not seem to recur.
- Refreshing the page or reloading Foundry does not fix the issue.
- I've tried with all modules turned off, still have this issue.

I also get this console error when it Foundry loads, not sure if it's related:

foundry.js:753 TypeError: Failed data preparation for Actor.z3m8PKyfiOQx4fKt. Cannot read properties of undefined (reading 'translate')
    at parseForRollOrDamage (parselink.js:57:35)
    at parselink (parselink.js:234:13)
    at GurpsActor._applyItemBonuses (actor.js:340:17)
    at GurpsActor.calculateDerivedValues (actor.js:248:8)
    at GurpsActor.prepareDerivedData (actor.js:165:8)
    at GurpsActor.prepareData (foundry.js:14212:12)
    at GurpsActor.prepareData (actor.js:104:9)
    at GurpsActor._safePrepareData (foundry.js:14187:14)
    at Game.initializeDocuments (foundry.js:8796:18)
    at Game.setupGame (foundry.js:8706:10)
    at async Game._initializeGameView (foundry.js:9990:5)

Running GGA 0.16.8 under FVTT V11 Stable Patch 13 (Build 315) on The Forge.

**Comment by mjeffw** [comment]
@SageThalcos Did this bug ever get resolved?

@chrismaille Have you looked at this?

**Comment by chrismaille** [comment]
I can't reproduce the issue. Line mentioned on the traceback is: https://github.com/crnormand/gurps/blob/37b834a63597aa8952924fa5cc48851fa066e08b/lib/parselink.js#L57, which suggests the global object `GURPS.DamageTables` is undefined at the time of the call.

In initial tests, it seems this code is invoked only when you open the character sheet when double-click the Token, not from the Actor list - and only when `gurpslink` method is calling. Not sure this is directly related to Foundry Items, chance will be on some OTF formula on the Actor. But this did not explain what the global object is not available.

@SageThalcos can you please provide a GCA/GCS exported file from one of the Actors you have the issue?

**Comment by rinickolous** [comment]
Can't reproduce this, and it may have been fixed. Closing for now, but please notify if the problem persists.
