### ISSUE TITLE
Errors occurring when users drop damage onto mooks/NPCs

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#2024]
From https://discord.com/channels/228546929494065152/788878698349723669/1302458969897566298

```
Players get "User lacks permission to update ActiveEffect" error message when mooks status changes in combat.

Last week we resumed our GURPS game after a hiatus of several months. I updated the GURPS Game Aid to the current release. Now in combat the players get error messages when mook take damage that results in a status change (especially when going from no status to reeling). Here is what shows in the logs:

foundry.js:72076 User Kirsten lacks permission to update ActiveEffect [FmyDLKVaBndg5gr0] in parent ActorDelta [tOGvVkReScjsw36B]
```

Console output for Player:

```
foundry.js:72076 User Kirsten lacks permission to update ActiveEffect [MHhVNmYdrQIPo27p] in parent ActorDelta [pSuMUJ9sV4Z8uo5W]
fetch @ foundry.js:72076
game:1 Uncaught (in promise) Error: User Kirsten lacks permission to update ActiveEffect [MHhVNmYdrQIPo27p] in parent ActorDelta [pSuMUJ9sV4Z8uo5W]
[No packages detected]
    at file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:5101
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async ServerDatabaseBackend._updateDocuments (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:4748)
    at async Semaphore._try (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:101:17) 

```

Console output for GM:

```
Foundry VTT | Rendering ApplyDamageDialog
2foundry-esm.js:56497 Uncaught (in promise) Error: undefined. You must provide an _id for every object in the update data Array.
[No packages detected]
    at #preUpdateDocumentArray (foundry-esm.js:56497:34)
    at async ClientDatabaseBackend._updateDocuments (foundry-esm.js:56469:7)
viewbox.js:150 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'control')
[Detected 1 package: LockView(1.5.10)]
    at drawViewbox (viewbox.js:150:95)
    at a.<anonymous> (socket.js:18:46)
    at U.emit (index.mjs:136:20)
    at a.value (socket.js:538:20)
    at a.value (socket.js:525:18)
    at a.value (socket.js:495:22)
    at U.emit (index.mjs:136:20)
    at manager.js:204:18
```

**Comment by chrismaille** [comment]
@mjeffw got this error too yesterday, during tests: `Uncaught (in promise) Error: undefined. You must provide an _id for every object in the update data Array.`

The errors i got started at:
* https://github.com/crnormand/gurps/blob/e02a5f926f18ec7d6ed715b79933c7f5f9eb1bd0/module/effects/active-effect.js#L121
* https://github.com/crnormand/gurps/blob/e02a5f926f18ec7d6ed715b79933c7f5f9eb1bd0/module/actor/actor.js#L858

System is now expecting a `document._id` or `collection._id` when you try to _setFlag_ the duration or _update_ the Actor. The later is simple to resolve (add `actor.id` to data) but for the first I not sure what type of `id` the setFlag needs, if they really need (maybe the operation must be outside the constructor, but I'm not sure about that). 

Please let me know if I can help. I'll debug again tonight.

**Comment by mjeffw** [comment]
So far my debugging has led me to believe that this is not related to document IDs. Even supplying the ID, or removing the line 121 from active-effect.js leads to the same error.

**Comment by mjeffw** [comment]
I got this figured out. Fix forthcoming.
